FROM nginx:alpine

# Apagar a config padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copiar config customizada
COPY nginx.conf /etc/nginx/conf.d

# Copiar os arquivos do seu projeto
COPY . /usr/share/nginx/html